version: '3.8'

services:
  climate-assistant:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
      - LLM_MODEL=llama3.1:8b
      - VECTOR_STORE_TYPE=faiss
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - DEBUG=False
    volumes:
      - ./data:/app/data
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  ollama_data:
